name:                image-compressor
version:             0.1.0.0
github:              "EpitechPromo2026/compressor"
license:             MIT
author:              "Florian Lauch, Lindon Aliu"
maintainer:          "florian.lauch@epitech.eu, lindon.aliu@epitech.eu"
copyright:           "2023 Florian Lauch"
description:         Please see the README on GitHub at <https://github.com/githubuser/image-compressor#readme>

dependencies:
- base >= 4.7 && < 5
- random
- optparse-applicative

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  imageCompressor:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - image-compressor

tests:
  testImageCompressor:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - image-compressor
    - HUnit
